#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The fork: measures DX7 voices as tools/level_presets.py measures the factory presets and writes
firmware/src/dx_trim.h: the level trim of each voice (1/2 dB, as preset_trim.h) by the hash of its sound, and the
two numbers of the estimate the firmware uses for a voice it does not know (eng_fm6.c dx_est, dx_trim_of).

  cc -O2 -Itests -Ibuild/gen -Ifirmware/src -Ifirmware/hal tests/dx_level.c -lm -o build/host/dx_level
  TRIMMED=1 build/host/dx_level build/host/dx.raw build/host/dx.txt BANK.syx...
  tools/level_dx.py build/host/dx.raw build/host/dx.txt
  (rebuild and run it again until nothing moves, as level_presets.py: each voice plays with the trim it has, and
  what is left is added — a trim step is not exactly 1/2 dB through the mix)

The banks are NOT in this repository (no voice data here): the owner's are in his homelab repo. The header holds
hashes and numbers only. Loudness, target and roles are level_presets.py's own (imported), so a DX7 voice lands
where the factory sounds do. Needs numpy and scipy."""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import level_presets as lp   # noqa: E402  (lufs, SEG, TARGET, ROLE)

OUT = Path(__file__).resolve().parent.parent / "firmware/src/dx_trim.h"


def main(raw, rep):
    rows = [l.split(None, 6) for l in Path(rep).read_text().splitlines()]
    d = np.fromfile(raw, np.int32).astype(float) / 32768.0
    meas = {}                                   # hash -> (trim wanted, estimate, name)
    moved = 0
    for i, (f, k, role, h, est, had, name) in enumerate(rows):
        L = lp.lufs(d[i * lp.SEG:(i + 1) * lp.SEG])
        if L is None:
            continue                            # silent: nothing to match
        want = int(had) + (lp.TARGET + lp.ROLE[int(role)] - L) * 2
        if int(had) < 23 or want < 23:          # (at the ceiling and still short: nothing left to give)
            moved += abs(round(want) - int(had)) > 0
        meas[int(h, 16)] = (want, int(est) / 256.0, name.strip())
    y = np.array([m[0] for m in meas.values()])
    x = np.array([m[1] for m in meas.values()])
    b, a = np.polyfit(x, y, 1)                  # the estimate: trim = a + b * dx_est
    err = a + b * x - y
    keep = np.abs(y) < 200
    print(f"{len(rows)} voices, {len(meas)} distinct sounds measured; the estimate (for voices not in the table): "
          f"rms {np.sqrt((err ** 2).mean()) / 2:.2f} dB, 90 % within {np.percentile(abs(err), 90) / 2:.2f} dB "
          f"(the trims themselves spread {y[keep].std() / 2:.2f} dB rms)")
    hs = sorted(meas)
    tr = [max(-40, min(23, int(round(meas[h][0])))) for h in hs]
    print(f"{sum(1 for h in hs if meas[h][0] > 23.5)} need more than the +23 ceiling (11.5 dB) and get the ceiling, "
          f"as the factory presets do")
    lines = ["/* generated by tools/level_dx.py: the level trim of DX7 voices measured on the host, 1/2 dB (as",
             " * preset_trim.h), by the FNV-1a hash of the 118 bytes of their sound (eng_fm6.c dx_hash); and the estimate",
             " * for any other voice: trim = (DX_EST_A + DX_EST_B * dx_est / 256) / 256 */",
             "#pragma once",
             f"#define DX_TRIM_N {len(hs)}u",
             f"#define DX_EST_A {int(round(a * 256))}",
             f"#define DX_EST_B {int(round(b * 256))}",
             "static const uint32_t DX_TRIM_HASH[DX_TRIM_N] = {"]
    for i in range(0, len(hs), 8):
        lines.append("    " + ", ".join(f"0x{h:08x}u" for h in hs[i:i + 8]) + ",")
    lines.append("};")
    lines.append("static const int8_t DX_TRIM[DX_TRIM_N] = {")
    for i in range(0, len(tr), 16):
        lines.append("    " + ", ".join(str(t) for t in tr[i:i + 16]) + ",")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(hs)} voices levelled -> {OUT}; {moved} trims moved this run (0: done)")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
